spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/easyexp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 192.168.1.4
    port: 6379
    password:
    timeout: 3600
    jedis:
      pool:
        max-active: 1000
        max-wait: 2000
        max-idle: 10
        min-idle: 1
        test-on-borrow: true
        test-while-idle: true
      timeout: 2000
  session:
    store-type: redis
  mail:
    host: smtp.qq.com
    username: 490359559@qq.com
    password: zxcvbn@123
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true
            required: true
    verification-code:
      code-length: 6
      valid-duration: 300000
      min-duration: 60000
      max-count-per-email: 5
logging:
  config: classpath:logback-local.xml

